config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments

  resources :sessions, :only => [:create]
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  get '/shifts/:id/start_now' => 'shifts#start_now'
  get '/shifts/:id/end_now' => 'shifts#end_now'
  
  # Set the root url
  root :to => 'home#home'  
  
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  # Callbacks
  before_save :reformat_phone
  before_validation :reformat_ssn
  before_destroy :is_destroyable?
  after_destroy :clean_up_assignment_and_shifts
  after_rollback :terminate_employee


  attr_reader :destroyable
  
  # Relationships
  has_many :assignments
  has_many :stores, through: :assignments
  has_one :user, dependent: :destroy
  has_many :shifts, through: :assignments


  accepts_nested_attributes_for :user, reject_if: lambda { |user| user[:email].blank? }, allow_destroy: true
  
  # Validations
  validates_presence_of :first_name, :last_name, :date_of_birth, :ssn, :role
  validates_date :date_of_birth, on_or_before: lambda { 14.years.ago }, on_or_before_message: "must be at least 14 years old"
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only", allow_blank: true
  validates_format_of :ssn, with: /\A\d{3}[- ]?\d{2}[- ]?\d{4}\z/, message: "should be 9 digits and delimited with dashes only"
  validates_inclusion_of :role, in: %w[admin manager employee], message: "is not an option"
  validates_uniqueness_of :ssn
  
  # Scopes
  scope :younger_than_18, -> { where('date_of_birth > ?', 18.years.ago.to_date) }
  scope :is_18_or_older,  -> { where('date_of_birth <= ?', 18.years.ago.to_date) }
  scope :active,          -> { where(active: true) }
  scope :inactive,        -> { where(active: false) }
  scope :regulars,        -> { where(role: 'employee') }
  scope :managers,        -> { where(role: 'manager') }
  scope :admins,          -> { where(role: 'admin') }
  scope :alphabetical,    -> { order('last_name, first_name') }
  
  # Other methods
  def name
    "#{last_name}, #{first_name}"
  end
  
  def proper_name
    "#{first_name} #{last_name}"
  end
  
  def current_assignment
    curr_assignment = self.assignments.select{|a| a.end_date.nil?}
    # alternative method for finding current assignment is to use scope 'current' in assignments:
    # curr_assignment = self.assignments.current    # will also return an array of current assignments
    return nil if curr_assignment.empty?
    curr_assignment.first   # return as a single object, not an array
  end
  
  def over_18?
    date_of_birth < 18.years.ago.to_date
  end
  
  def age
    (Time.now.to_s(:number).to_i - date_of_birth.to_time.to_s(:number).to_i)/10e9.to_i
  end
  
  # Misc Constants
  ROLES_LIST = [['Employee', 'employee'],['Manager', 'manager'],['Administrator', 'admin']]
  
  
  # Callback code  (NOT DRY!!!)
  # -----------------------------
  private
  def reformat_phone
    phone = self.phone.to_s  # change to string in case input as all numbers 
    phone.gsub!(/[^0-9]/,"") # strip all non-digits
    self.phone = phone       # reset self.phone to new string
  end

  def reformat_ssn
    ssn = self.ssn.to_s      # change to string in case input as all numbers 
    ssn.gsub!(/[^0-9]/,"")   # strip all non-digits
    self.ssn = ssn           # reset self.ssn to new string
  end

  def is_destroyable?
    @destroyable = self.shifts.past.empty?
  end

  def remove_upcoming_shifts
    @future_shifts = self.shifts.upcoming
    @future_shifts.each {|s| s.destroy} unless @future_shifts.empty?
  end

  def clean_up_assignment_and_shifts
    if @destroyable
      remove_upcoming_shifts
      self.current_assignment.delete unless self.current_assignment.nil?
    end
    @destroyable = nil
  end

  def end_current_assignment
    current_assignment = self.current_assignment    
    unless current_assignment.nil?
      current_assignment.update_attribute(:end_date, Date.current)
    end
  end

  def terminate_employee
    if !@destroyable.nil? && @destroyable == false
      remove_upcoming_shifts
      end_current_assignment
    end
    @destroyable = nil
  end

end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  check_authorization
  load_and_authorize_resource
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  
  def index
    @active_employees = Employee.active.alphabetical.select{ |e| can? :read, e}.to_a.paginate(:page => params[:active_employees_page], :per_page => 10)
    @inactive_employees = Employee.inactive.alphabetical.select{ |e| can? :read, e}.to_a.paginate(:page => params[:inactive_employees_page], :per_page => 10)
  end

  def show
    @assignments = @employee.assignments.chronological.to_a.paginate(:page => params[:assignments_page], :per_page => 7)
    @user = @employee.user
  end

  def new
    @employee = Employee.new
    @employee.build_user
    @employee.date_of_birth = 20.years.ago
  end

  def edit
  end

  def create
    @update_employee = employee_params
    @update_employee[:date_of_birth] = Date.strptime(employee_params[:date_of_birth].to_s, "%m/%d/%Y") 
    @employee = Employee.new(@update_employee)
    @employee.date_of_birth = @employee.date_of_birth.to_s.to_date 
    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: "Successfully created #{@employee.proper_name}."}
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @update_employee = employee_params
    @update_employee[:date_of_birth] = Date.strptime(employee_params[:date_of_birth].to_s, "%m/%d/%Y")      
    if @employee.update(@update_employee)
      redirect_to employee_path(@employee), notice: "Successfully updated #{@employee.proper_name}."
    else
      render action: 'edit'
    end
  end

  def destroy
    @employee.destroy
    redirect_to employees_path, notice: "Successfully removed #{@employee.proper_name} from the AMC system."
  end

  private
  def set_employee
    @employee = Employee.find(params[:id])
  end

  def employee_params
    if @current_user == "employee" then
      params.require(:employee).permit(:first_name, :last_name, :date_of_birth, :phone, :active, user_attributes: [:id, :email, :password_confirmation, :password, :employee_id, :_destroy])
    else
      params.require(:employee).permit(:first_name, :last_name, :ssn, :date_of_birth, :role, :phone, :active, user_attributes: [:id, :email, :password_confirmation, :password, :employee_id, :_destroy])
    end
  end

end

app/views/employees/_assignment_history.html.erb
<div id="assignment_from_employee_list">
  <% if @assignments.count > 0 then %>
    <h3>Assignment History</h3>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Store</th>
          <th class="centered">Start Date</th>
          <th class="centered">End Date</th>
          <th class="centered">Pay Level</th>
          <th></th>
          <% if can? :update, Assignment %>
            <th></th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @assignments.each do |assignment| %>
          <% if can? :read, assignment %>
            <tr>
              <td><%= link_to assignment.store.name, store_path(assignment.store) %></td>
              <td>
                <%= assignment.start_date.strftime("%m/%d/%y") %>         
              </td>
              <td class="centered">
                <% if assignment.end_date.nil? %>
                  <% if can? :update, Assignment %>   
                    &nbsp;&nbsp;&nbsp;
                    <%= link_to 'End', assignment, method: :end_assignment, remote: true%>
                  <% else %> 
                    --
                  <% end %>                  
                <% else %>
                  <%= assignment.end_date.strftime("%m/%d/%y") %>
                <% end %>    
              </td>          
              <td class="centered"><%= assignment.pay_level %></td>
              <td><%= link_to 'View Details', assignment_path(assignment) %></td>
              <% if can? :update, Assignment %>
                <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>        
              <% end %>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "assignments_page" %>
  <% else %>
    <h3>No Associated Assignments</h3>
  <% end %>
</div>  

app/views/employees/_current_employees.html.erb
<% if @active_employees.empty? %>
  <p><em>There are no current employees at this time.</em></p>
<% else %>
  <fieldset>
    <legend><h3>Current Employees</h3></legend>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Phone</th>
          <th>Currently Assigned</th>
          <th>Role</th>
          <% if can? :read, @active_employees.first %>
            <th></th>
          <% end %>        
          <% if can? :update, @active_employees.first %>
            <th></th>
          <% end %>
          <% if can? :destroy, @active_employees.first %>
            <th></th>
          <% end %>          
        </tr>
      </thead>
      <tbody>
        <% @active_employees.each do |employee| %>
          <tr>
            <td><%= employee.name %></td>
            <td><a href="tel:<%= number_to_phone employee.phone %>"><%= number_to_phone employee.phone unless employee.phone.nil? %></td>
            <td><%= link_to employee.current_assignment.store.name, store_path(employee.current_assignment.store) unless employee.current_assignment.nil? %></td>
            <td><%= employee.role.capitalize %></td>
            <% if can? :read, employee %>
              <td><%= link_to 'View Details', employee_path(employee) %></td>   
            <% end %>       
            <% if can? :update, employee %>
              <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
            <% end %>
            <% if can? :destroy, employee %>
              <td><%= link_to 'Deactivate', employee, method: :delete %></td>
            <% end %>            
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @active_employees, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "active_employees_page" %>
  </fieldset>
<% end %>

app/views/employees/_employee_details.html.erb
<fieldset>
  <legend><h3><%= @employee.proper_name %>'s Details</h3></legend>
  <p>
    <b>SSN:</b> <%= @employee.ssn %>
  </p>

  <p>
    <b>Date of Birth:</b> <%= @employee.date_of_birth.strftime("%m/%d/%Y") %>
  </p>

  <p>
    <b>Phone:</b> 
    <% unless @employee.phone.nil? %>
      <a href="tel:<%= number_to_phone @employee.phone %>"><%= number_to_phone @employee.phone %></a>
    <% end %>
  </p>

  <p>
    <b>Role:</b> <%= @employee.role.capitalize %>
  </p>

  <p>
    <b>Active:</b> <%= @employee.active ? "Yes" : "No" %>
  </p>

  <% if @user then %>
    <p>
     <b>Email:</b> <a href="mailto:<%= @user.email %>"><%= @user.email %></a>
    </p>
  <% end %>
</fieldset>

app/views/employees/_employee_fields.html.erb
<%= f.error_notification %>   
<%= f.input :first_name %>
<%= f.input :last_name %>
<% if can? :update_ssn, Employee %>
  <%= f.input :ssn %>
<% else %>
  SSN: <%= f.object.ssn %>
  <br>
  You do not have sufficient privledges to update your SSN. Please contact an administrator.
<% end %>
<%= f.text_field :date_of_birth, :id => "employeedatepicker", label: 'Birth Date', :value => @employee.date_of_birth.to_date.strftime("%m/%d/%Y") %>
<%= f.input :phone %>
<% if can? :update_role, Employee %>
  <%= f.input :role, as: :select, collection: Employee::ROLES_LIST %>
<% end %>

<%= f.input :active %>

app/views/employees/_form.html.erb
<%= simple_nested_form_for @employee, :html => { :class => 'form-horizontal' } do |employee_form| %>
  <div class="row">
    <div class="span7">
      <fieldset>
        <legend><%= controller.action_name.capitalize %> Employee</legend>     
        <%= render :partial => "employee_fields", :locals => { :f => employee_form } %>
      </fieldset>
    </div>
    <div class="span5">
      <legend>User</legend>
      <div id="employee_user">
        <%= employee_form.simple_fields_for :user do |f| %>
          <%= f.error_notification %>        
          <%= f.input :email %>
          <%= f.input :password %>
          <%= f.input :password_confirmation %>
          <%= f.input :employee_id, as: :hidden, input_html: { value: @employee.id } %>     
        <% end %> 
      </div> 
    </div>
  </div>
  <div class="form-actions">
    <%= employee_form.submit nil, :class => 'button radius' %>
    <% if @employee.id.nil? %>
      <% @path = employees_path %>
    <% else %>
      <% @path = employee_path(@employee) %>
    <% end %>
    <%= link_to 'Cancel', @path, :class => 'button secondary alert' %>
  </div>
<% end %>

app/views/employees/_inactive_employees.html.erb
<% if can? :read_inactive_employee, Employee %>
  <% unless @inactive_employees.empty? %>
    <div class="panel callout radius">
      <h3>Inactive Employees</h3>
      <ul>
        <% @inactive_employees.each do |employee| %>
          <li><%= link_to employee.name, employee_path(employee) %></li>
        <% end %>
      </ul>
    </div>
  <% else %>
    <h3>No Inactive Employees</h3>
  <% end %>
<% end %>

app/views/employees/_store_details.html.erb
<p>
  <h4>
    Name: <%= @store.name %>
  </h4>
</p>

<p>
  <b>Address:</b><br>
  <%= @store.street %><br />
  <%= @store.city %>, <%= @store.state %> <%= @store.zip %>
</p>

<p>
  <b>Phone:</b><br>
  <%= number_to_phone @store.phone %>
</p>

<p>
  <b>Active:</b> 
  <%= @store.active ? "Yes" : "No" %>
</p>

app/views/employees/_user_fields.html.erb
<%= f.error_notification %>  
<%= f.input :email %>
<%= f.input :password %>
<%= f.input :password_confirmation %>
<%= f.input :employee_id, as: :hidden, input_html: { value: @employee } %>

app/views/employees/edit.html.erb
<%= render :partial => "partials/display_form" %>

app/views/employees/end_assignment.js.erb
$('#assignment_list').replaceWith('<%= j render("employees/assignment_history") %>');

app/views/employees/index.html.erb
<%= render partial: "partials/index_structure", locals: {model_name: "employee", 
                                                         primary: "current_employees", 
                                                         secondary: nil,
                                                         sidebar: "inactive_employees"} %>

app/views/employees/new.html.erb
<%= render :partial => "partials/display_form" %>

app/views/employees/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render partial: "employee_details" %>
  </div>
  <div class="small-5 columns">
    <%= render partial: "assignment_history" %>
    <% if can? :create, Assignment %>
      <%= link_to 'Add an Assignment', new_assignment_path(employee_id: @employee.id), class: "button", id: "new_employee_assignment_link", remote: true %>
    <% end %>
  </div>
</div>

<%= render partial: "partials/object_options", locals: {model_name: "employee", object: @employee}  %>