config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments

  resources :sessions, :only => [:create]
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  get '/shifts/:id/start_now' => 'shifts#start_now'
  get '/shifts/:id/end_now' => 'shifts#end_now'
  
  # Set the root url
  root :to => 'home#home'  
  
end

app/models/store.rb
class Store < ActiveRecord::Base
  # Callbacks
  before_save :reformat_phone
  before_destroy :is_destroyable?
  after_rollback :convert_to_inactive

  
  # Relationships
  has_many :assignments
  has_many :employees, through: :assignments  
  has_many :shifts, through: :assignments
  has_many :store_flavors
  has_many :flavors, through: :store_flavors
  
  # Validations
  # make sure required fields are present
  validates_presence_of :name, :street, :zip
  # if state is given, must be one of the choices given (no hacking this field)
  validates_inclusion_of :state, :in => %w[PA OH WV], message: "is not an option"
  # if zip included, it must be 5 digits only
  validates_format_of :zip, with: /\A\d{5}\z/, message: "should be five digits long"
  # phone can have dashes, spaces, dots and parens, but must be 10 digits
  validates_format_of :phone, with: /\A\(?\d{3}\)?[-. ]?\d{3}[-.]?\d{4}\z/, message: "should be 10 digits (area code needed) and delimited with dashes only"
  # make sure stores have unique names
  validates_uniqueness_of :name
  
  # Scopes
  scope :alphabetical, -> { order('name') }
  scope :active,       -> { where(active: true) }
  scope :inactive,     -> { where(active: false) }
  
  
  # Misc constants
  STATES_LIST = [['Ohio', 'OH'],['Pennsylvania', 'PA'],['West Virginia', 'WV']]
  
  # Other methods
  def get_store_coordinates
    coord = Geocoder.coordinates("#{street}, #{zip}")
    if coord
      self.latitude = coord[0]
      self.longitude = coord[1]
      self.save
    end
    coord
  end
  
  # mapping
  def create_map_link(zoom=12,width=800,height=800)
    markers = "&markers=color:red%7Ccolor:red%7Clabel:1%7C#{self.latitude},#{self.longitude}"
    map = "http://maps.google.com/maps/api/staticmap?center=#{latitude},#{longitude}&zoom=#{zoom}&size=#{width}x#{height}&maptype=roadmap#{markers}&sensor=false"
  end

  # Callback code
  # -----------------------------
  private
  # We need to strip non-digits before saving to db
  def reformat_phone
    phone = self.phone.to_s  # change to string in case input as all numbers 
    phone.gsub!(/[^0-9]/,"") # strip all non-digits
    self.phone = phone       # reset self.phone to new string
  end

  def is_destroyable?
    @destroyable = false
  end
  
  def convert_to_inactive
    make_inactive if !@destroyable.nil? && @destroyable == false
    @destroyable = nil
  end

  def make_inactive
    self.update_attribute(:active, false)
  end

end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  check_authorization
  load_and_authorize_resource
  before_action :set_store, only: [:show, :edit, :update, :destroy]
  
  def index
    @active_stores = Store.active.alphabetical.to_a.paginate(:page => params[:active_stores_page], :per_page => 10)
    @inactive_stores = Store.inactive.alphabetical.to_a.paginate(:page => params[:inactive_stores_page], :per_page => 10)
  end

  def show
    @current_assignments = @store.assignments.current.by_employee.to_a.paginate(:page => params[:current_assignments_page], :per_page => 7)
    @flavors = @store.store_flavors.to_a.paginate(:page => params[:flavors_page], :per_page => 5)
    @employee = Employee.new
    @employee.id = 0
    if @store.latitude.nil? and @store.latitude.nil? then
      @store.get_store_coordinates
    end
  end

  def new
    @store = Store.new
  end

  def edit
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      @store.get_store_coordinates
      redirect_to store_path(@store), notice: "Successfully created #{@store.name}."
    else
      render action: 'new'
    end
  end

  def update
    if @store.update(store_params)
      @store.get_store_coordinates      
      redirect_to store_path(@store), notice: "Successfully updated #{@store.name}."
    else
      render action: 'edit'
    end
  end

  def destroy
    @store.destroy
    redirect_to stores_path, notice: "Successfully removed #{@store.name} from the AMC system."
  end

  private
  def set_store
    @store = Store.find(params[:id])
  end

  def store_params
    params.require(:store).permit(:name, :street, :city, :state, :zip, :phone, :active)
  end

end

app/views/stores/_active_stores.html.erb
<% if @active_stores.empty? %>
  <p><em>There are no active stores at this time.</em></p>
<% else %>
  <fieldset>
    <legend><h3>Active Stores</h3></legend>
    <table class="table table-striped">
      <thead>
        <tr>
          <th width="225">Store Name</th>
          <th width="225">Store Phone</th>
          <% if can? :read, Assignment %>
            <th width="125">Staff Count</th>
          <% end %>
          <% if can? :update, @store %>
            <th width="75">&nbsp;</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @active_stores.each do |store| %>
          <tr>
            <td><%= link_to store.name, store_path(store) %></td>
            <td><a href="tel:<%= number_to_phone store.phone %>"><%= number_to_phone store.phone %></td>
              <% if can? :read, Assignment %>
                <% if can? :read, Assignment.for_store(store).first %>           
                  <td><%= link_to store.assignments.current.count, employees_path %></td>      
                <% else %>
                  <td></td>
                <% end %>
              <% end %>
              <% if can? :update, @store %>
                <td><%= link_to(edit_store_path(store)) do %>Edit<% end %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @active_stores, previous_label: "Previous&nbsp;", next_label: "&nbsp;Next", param_name: 'active_stores_page' %>
  </fieldset>
<% end %>

app/views/stores/_assigned_employees.html.erb
<% if @current_assignments.select{ |a| can? :read, a }.length > 0 %>
  <div id="assignment_list">
    <% if @current_assignments.count > 0 then %>
      <h4>Current Employees at <%= @store.name.split.map(&:capitalize).join(' ') %></h4>  
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Name</th>
                <th class="centered">Pay Level</th>
                <th>Start Date</th>
                <th></th>           
                <% if can? :update, Assignment %>               
                  <td>End Assignment</th>
                <% end %>
                <% if can? :destroy, Assignment %>               
                  <th></th> 
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% @current_assignments.each do |assignment| %>
                <tr>
                  <td><%= link_to assignment.employee.name, employee_path(assignment.employee) %></td>
                  <td class="centered"><%= assignment.pay_level %></td> 
                  <td><%= assignment.start_date.strftime("%m/%d/%y") %></td>
                  <td><%= link_to 'View Details', assignment_path(assignment) %></td>                  
                  <% if can? :update, Assignment %>            
                    <td><%= link_to 'Edit', edit_assignment_path(assignment) %></td>               
                  <% end %>
                  <% if can? :destroy, Assignment %>
                    <td><%= link_to 'End Now', assignment_path(assignment), :method => :delete, remote: true %></td>   
                  <% end %>     
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= will_paginate @current_assignments, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next" , :param_name => 'current_assignments_page' %>
        <% else %>
          <h4>No Current Employees at <%= @store.name.capitalize %></h4>
        <% end %>
      </div>
    <% end %>

app/views/stores/_form.html.erb
<%= simple_form_for @store, html: { class: 'form-horizontal' } do |f| %>
  <fieldset>
    <legend><%= controller.action_name.capitalize %> Store</legend>
    <%= f.error_notification %>
    <%= f.input :name, input_html: {class: "avg"} %>
    <%= f.input :street, input_html: {class: "avg"} %>
    <%= f.input :city, input_html: {class: "avg"} %>
    <%= f.input :state, collection: Store::STATES_LIST, include_blank: true, input_html: {class: "avg"} %>
    <%= f.input :zip, input_html: {class: "avg"} %>
    <%= f.input :phone, input_html: {class: "avg"} %>
    <%= f.input :active %>

    <div class="form-actions">
      <%= f.submit nil, :class => 'button radius' %>
      <%= link_to 'Cancel', stores_path, :class => 'button alert radius' %>
    </div>
  </fieldset>
<% end %>

app/views/stores/_inactive_stores.html.erb
<% if can? :read_inactive, Store %>
  <% unless @inactive_stores.empty? %>
    <fieldset>
      <legend><h3>Inactive Stores</h3></legend>
      <ul>
        <% @inactive_stores.each do |store| %>
          <li><%= link_to store.name, store_path(store) %></li>
        <% end %>
      </ul>
    </fieldset>
  <% else %>
      <h3>No Inactive Stores to Display</h3>
  <% end %>
<% end %>

app/views/stores/_list_flavors.html.erb
<div id="flavor_list">
  <% if @flavors.count > 0 then %>
    <h4>Flavors at <%= @store.name.capitalize.split.map(&:capitalize).join(' ') %></h4>
    <table class="table table-striped">
      <thead>
        <tr>
          <%if can? :read, @flavors.first.flavor %>
            <th>Flavor</th>
          <% end %>
          <% if can? :update, @flavors.first.flavor %>
            <th></th>
          <% end %>          
          <% if can? :destroy, @flavors.first %>
            <th></th>
          <% end %>    
        </tr>
      </thead>
      <tbody>
        <% @flavors.each do |sf| %>
          <tr>
            <% if can? :read, sf.flavor %>
              <td><%= link_to sf.flavor.name, flavor_path(sf.flavor) %></td>
            <% end %>    
            <% if can? :update, sf.flavor %>   
              <td><%= link_to 'Edit Flavor', edit_flavor_path(sf.flavor) %></td>
            <% end %>  
            <% if can? :destroy, sf %>
              <td><%= link_to 'Remove Flavor from Store', store_flavor_path(sf), :method => :delete, remote: true %></td>
            <% end %>          
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @flavors, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "flavors_page" %>    
  <% else %>
    <h4>No Favors at <%= @store.name.capitalize %></h4>
  <% end %>
</div>

app/views/stores/_store_details.html.erb
<fieldset>
  <legend><h3><%= @store.name %>'s Details</h3></legend>
  <p>
    <b>Address:</b><br>
    <a href="http://maps.google.com/?q=<%= @store.street %> <%= @store.city %>, <%= @store.state %> <%= @store.zip %>">
      <%= @store.street %><br />
      <%= @store.city %>, <%= @store.state %> <%= @store.zip %>
    </a>
  </p>

  <p>
    <b>Phone:</b>
    <a href="tel:<%= number_to_phone @store.phone %>"><%= number_to_phone @store.phone %></a>
  </p>

  <p>
    <b>Active:</b> 
    <%= @store.active ? "Yes" : "No" %>
  </p>

  <p>
    <%= image_tag @store.create_map_link %>
  </p>
</fieldset>

app/views/stores/edit.html.erb
<%= render :partial => "partials/display_form" %>

app/views/stores/index.html.erb
<%= render partial: "partials/index_structure_3", locals: {model_name: "store", 
                                                         primary: "active_stores", 
                                                         secondary: nil,
                                                         sidebar: "inactive_stores"} %>

app/views/stores/new.html.erb
<%= render :partial => "partials/display_form" %>

app/views/stores/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render partial: "store_details" %>
  </div>
  <div class="small-5 columns">
    <%= render partial: "list_flavors" %>
    <% if can? :create, @flavors.first and @store.active %>
      <%= link_to(new_store_flavor_path(store_id: @store.id), class: 'button small radius', id: 'new_store_flavor_link', remote: true) do %>
        Assign New Flavor
      <% end %>
    <% end %>
  </div>

    <div class="small-5 columns">  
      <%= render partial: "assigned_employees"%>
      <% if can? :create, Assignment and @store.active %>      
        <%= link_to(new_assignment_path(store_id: @store.id), class: 'button small radius', id: 'new_assignment_link', remote: true) do %>
          New Employee Assignment
        <% end %>    
      <% end %>
    </div>


</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "store", object: @store}  %>