config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments

  resources :sessions, :only => [:create]
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  get '/shifts/:id/start_now' => 'shifts#start_now'
  get '/shifts/:id/end_now' => 'shifts#end_now'
  
  # Set the root url
  root :to => 'home#home'  
  
end

app/views/partials/_address_info.html.erb
  <%= store.street %><br />
  <%= store.city %>, <%= store.state %> <%= store.zip %>

app/views/partials/_display_form.html.erb
<div class="row">
  <div class="small-8 columns">
    <%= render :partial => "form" %>
  </div>
</div>

app/views/partials/_flash.html.erb
<% flash.each do |name, msg| %>
  <div data-alert data-options="animation_speed:500, animation:'fadeOut';" class="alert-box <%= flash[:notice] ? "success" : "warning" %> radius">
    <a href="#" class="close">&times;</a>
    <%= msg %>
  </div>
<% end %>

app/views/partials/_footer.html.erb
<footer>

	<%= link_to 'Home', home_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
  <%= link_to 'About the Creamery', about_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Contact Us', contact_path %>&nbsp;&nbsp;::&nbsp;&nbsp;
	<%= link_to 'Privacy Policy', privacy_path %>
	<br /><br />
	
	<div id="copy">
		Web Slinger: <%= mail_to("jalee@cmu.edu", "JEREMY LEE", encode: "javascript") %> 
		&nbsp;&nbsp;&copy 2016
	</div>

</footer>

app/views/partials/_index_structure.html.erb
<div class="row">
  <div class="small-8 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-4 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add a button for new instances of object -->
<% if can? :create, eval("@#{model_name}") %>
  <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
    <!-- <i class="fa fa-plus"></i> -->
    &nbsp;Add a New <%= model_name.capitalize %>
  <% end %>
<% end %>

app/views/partials/_index_structure_2.html.erb
<div class="row">
  <div class="small-9 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-3 columns">
    <!-- Add a button for new instances of object -->
    <% if can? :create, eval("@#{model_name}") %>
      <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
        Add a New <%= model_name.capitalize %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/partials/_index_structure_3.html.erb
<div class="row">
  <div class="small-6 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-6 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>


    <!-- Add a button for new instances of object -->
    <% if can? :create, eval("@#{model_name}") %>
      <%= link_to(eval("new_#{model_name}_path"), class: "button radius") do %>
        <!-- <i class="fa fa-plus"></i> -->
        &nbsp;Add a New <%= model_name.capitalize %>
      <% end %>
    <% end %>
  </div>
</div>

app/views/partials/_nav.html.erb
<div class="contain-to-grid">
  <nav class="top-bar" data-topbar role="navigation"> 
    <section class="top-bar-section">
      <ul class="left">
        <!-- link to home -->
        <li><%= link_to "Home", home_path %></li>

        <!-- options for stores -->
        <% if can? :index, Store %>        
          <li class="has-dropdown">
              <%= link_to "Stores", stores_path %>
              <ul class="dropdown">
                <% unless current_user.nil? or Assignment.for_employee(current_user.employee).current.first.nil? %>
                  <li><%= link_to "My Store", store_path(Assignment.for_employee(current_user.employee).current.first.store_id) %></li>
                <% end %>
                <% if can? :index, Store %>
                  <li><%= link_to "Store List", stores_path %></li>
                <% end %>
                <% if can? :create, Store %>
                  <li><%= link_to "Add a Store", new_store_path %></li>
                <% end %>
              </ul>
          </li>
        <% end %>        

        <!-- options for employees -->
        <% if can? :index, Employee %>        
          <li class="has-dropdown">
              <%= link_to "Employees", employees_path %>
              <ul class="dropdown">
                <% if can? :read, current_user.employee %>
                  <li><%= link_to "My Employee Info", employee_path(current_user.employee) %></li>
                <% end %>
                <% if can? :index, Employee %>
                  <li><%= link_to "Employee List", employees_path %></li>
                <% end %>
                <% if can? :create, Employee %>
                  <li><%= link_to "Add an Employee", new_employee_path %></li> 
                <% end %>
              </ul>
          </li>
        <% end %>

        <!-- options for assignments -->
        <% if can? :index, Assignment %>          
          <li class="has-dropdown">
            <%= link_to "Assignments", assignments_path %>
            <ul class="dropdown">
              <% unless Assignment.for_employee(current_user.employee).current.first.nil? %>        
                  <li><%= link_to "My Current Assignment", assignment_path(Assignment.for_employee(current_user.employee).current.first) %></li>
              <% end %>     
              <% if can? :index, Assignment %>     
                <li><%= link_to "Assignments List", assignments_path %></li>
              <% end %>
              <% if can? :create, Assignment %>
                <li><%= link_to "Create New Assignment", new_assignment_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>

        <!-- options for shifts -->
        <% if can? :index, Shift %>          
          <li class="has-dropdown">
            <%= link_to "Shifts", shifts_path %>
            <ul class="dropdown">
              <% unless Assignment.for_employee(current_user.employee).current.first.nil? %>        
                  <li><%= link_to "My Shifts", assignment_path(Assignment.for_employee(current_user.employee).current.first) %></li>
              <% end %>     
              <% if can? :index, Shift %>     
                <li><%= link_to "Shifts List", shifts_path %></li>
              <% end %>
              <% if can? :create, Shift %>
                <li><%= link_to "Create New Shift", new_shift_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>      

        <!-- options for flavor -->
        <% if can? :index, Flavor %>          
          <li class="has-dropdown">
            <%= link_to "Flavors", flavors_path %>
            <ul class="dropdown">  
              <% if can? :index, Flavor %>     
                <li><%= link_to "Flavors List", flavors_path %></li>
              <% end %>
              <% if !current_user.nil? and Assignment.for_employee(current_user.employee).current.first != nil and can? :create, StoreFlavor %>
                <li><%= link_to "Assign a Flavor", store_path(Assignment.for_employee(current_user.employee).current.first.store_id) %></li>
              <% end %>              
              <% if can? :create, Flavor %>
                <li><%= link_to "Create New Flavor", new_flavor_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>  

        <!-- options for job -->
        <% if can? :index, Job %>          
          <li class="has-dropdown">
            <%= link_to "Jobs", jobs_path %>
            <ul class="dropdown">  
              <% if can? :index, Job %>     
                <li><%= link_to "Jobs List", jobs_path %></li>
              <% end %>           
              <% if can? :create, Job %>
                <li><%= link_to "Create New Job", new_job_path %></li>
              <% end %>
            </ul>
          </li>
        <% end %>  

    </section>
  </nav>
</div>

app/views/partials/_object_options.html.erb
  <% opt = "#{object.respond_to?(:name) ? object.name : model_name.capitalize }" %>

  <div class="form-actions">
    <% if can? :index, eval("@#{model_name}") %>
      <%= link_to(eval("#{model_name.pluralize}_path"), class: 'button radius') do %>
        &nbsp;Display All <%= model_name.pluralize.capitalize %>
      <% end %>
    <% end %>

    <% if can? :update, eval("@#{model_name}") %>    
      <%= link_to(eval("edit_#{model_name}_path(object)"), class: 'button radius') do %>
          &nbsp;<%= "Edit #{opt}" %>
      <% end %>
    <% end %>
    &nbsp;&nbsp;
    
    <% if can? :destroy, eval("@#{model_name}") %>     
      <%= link_to(eval("#{model_name}_path(object)"), method: 'delete', data: {confirm: "Are you sure you want to permanently delete #{opt}"}, class: 'button radius alert') do %>
          &nbsp;<%= "Delete #{opt}" %>
      <% end %>
    <% end %>
  </div>

app/views/partials/_show_structure.html.erb
<div class="row">
  <div class="small-7 columns">
    <!-- primary partial gets displayed here in main div -->
    <%= render partial: "#{primary}" %>
    <!-- sometimes we want another partial below -->
    <% unless secondary.nil? %>
      <p>&nbsp;</p>
      <%= render partial: "#{secondary}" %>
    <% end %>
    
  </div>
  <div class="small-5 columns">
    <!-- render the sidebar, if it exists -->
    <%= render partial: "#{sidebar}" unless sidebar.blank? %>
  </div>
</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "#{model_name}", object: @object}  %>