config/routes.rb
Rails.application.routes.draw do
  # Routes for main resources
  resources :users
  resources :store_flavors
  resources :flavors
  resources :jobs
  resources :shift_jobs
  resources :shifts
  # Routes for main resources
  resources :stores
  resources :employees
  resources :assignments

  resources :sessions, :only => [:create]
  get 'login' => 'sessions#new', :as => :login
  get 'logout' => 'sessions#destroy', :as => :logout

  # Semi-static page routes
  get 'home' => 'home#home', as: :home
  get 'about' => 'home#about', as: :about
  get 'contact' => 'home#contact', as: :contact
  get 'privacy' => 'home#privacy', as: :privacy

  get '/shifts/:id/start_now' => 'shifts#start_now'
  get '/shifts/:id/end_now' => 'shifts#end_now'
  
  # Set the root url
  root :to => 'home#home'  
  
end

app/models/shift.rb
class Shift < ActiveRecord::Base
  # Relationships
  has_many :shift_jobs
  has_many :jobs, through: :shift_jobs
  belongs_to :assignment
  has_one :employee, through: :assignment
  has_one :store, through: :assignment

  # Validations
  validates_date :date, on_or_after: lambda { :assignment_starts }, on_or_before_message: "must be on or after the start of the assignment"
  validates_time :start_time
  validates_time :end_time, after: :start_time, allow_blank: true
  validate :assignment_must_be_current

  # Scopes
  scope :chronological, -> { order(:date, :start_time) }
  scope :by_store, -> { joins(:assignment, :store).order('stores.name') }
  scope :by_employee, -> { joins(:assignment, :employee).order('employees.last_name, employees.first_name') }
  scope :past, -> { where('date < ?', Date.current) }
  scope :upcoming, -> { where('date >= ?', Date.current) }
  scope :for_employee, ->(employee_id) { joins(:assignment, :employee).where("assignments.employee_id = ?", employee_id) }
  scope :for_store, ->(store_id) { joins(:assignment, :store).where("assignments.store_id = ?", store_id) }
  scope :for_next_days, ->(x) { where('date BETWEEN ? AND ?', Date.today, x.days.from_now.to_date) }
  scope :for_past_days, ->(x) { where('date BETWEEN ? AND ?', x.days.ago.to_date, 1.day.ago.to_date) }
  scope :completed, -> { joins(:shift_jobs).group(:shift_id) }
  scope :incomplete, -> { joins("LEFT JOIN shift_jobs ON shifts.id = shift_jobs.shift_id").where('shift_jobs.job_id IS NULL') }
  # alternative ways of finding 'incomplete' scope:
  # scope :incomplete, -> { where('id NOT IN (?)', Shift.completed.map(&:id)) }
  # a class method to also find incomplete shifts using array operations...
  def self.not_completed
    all_shifts = Shift.all
    completed_shifts = Shift.completed
    incompleted_shifts = all_shifts - completed_shifts
  end

  # Other methods
  def completed?
    self.shift_jobs.count > 0
  end

  def start_now
    self.update_attribute(:start_time, Time.current - 4.hours)
  end

  def end_now
    self.update_attribute(:end_time, Time.current - 4.hours)
  end

  def duration
    # returns the duration of the shift in units of hours (fractional)
    # since creamery not opened past midnight, don't have to
    # worry about crossing into next day, so just ...
    (self.end_time - self.start_time)/3600.0
  end
  
  # callback to set default end_time (on create only)
  before_create :set_shift_end_time
  
  private
  def assignment_starts
    @assignment_starts = self.assignment.start_date.to_date
  end
  
  def assignment_must_be_current
    unless self.assignment.nil? || self.assignment.end_date.nil?
      errors.add(:assignment_id, "is not a current assignment at the creamery")
    end
  end
  
  def set_shift_end_time
    self.end_time = self.start_time + (3*60*60)
  end

end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  check_authorization
  load_and_authorize_resource
  before_action :set_shift, only: [:show, :edit, :update, :destroy, :start_now, :end_now]

  # GET /shifts
  # GET /shifts.json
  def index
    @shifts = Shift.select{ |s| can? :read, s}.to_a.paginate(:page => params[:shifts_page], :per_page => 15)
  end

  # GET /shifts/1
  # GET /shifts/1.json
  def show
    @shift_jobs = @shift.shift_jobs.select{ |sj| can? :read, sj}.to_a.paginate(:page => params[:shift_jobs_page], :per_page => 7)
  end

  # GET /shifts/new
  def new
    @shift = Shift.new
    @shift.date = Date.current
  end

  # GET /shifts/1/edit
  def edit
  end

  # POST /shifts
  # POST /shifts.json
  def create
    @update_shift = shift_params
    @update_shift[:date] = Date.strptime(shift_params[:date].to_s, "%m/%d/%Y")   
    @shift = Shift.new(@update_shift)
    @assignment = @shift.assignment
    respond_to do |format|
      if @shift.save
        @shifts = @assignment.shifts.select{ |s| can? :read, s}.to_a.paginate(:page => params[:shifts_page], :per_page => 8)         
        format.js
        format.html { redirect_to @shift, notice: 'Shift was successfully created.' }
        format.json { render :show, status: :created, location: @shift }
      else
        format.html { render :new }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shifts/1
  # PATCH/PUT /shifts/1.json
  def update 
    @update_shift = shift_params
    @update_shift[:date] = Date.strptime(shift_params[:date].to_s, "%m/%d/%Y")
    respond_to do |format|
      if @shift.update(@update_shift)
        format.html { redirect_to @shift, notice: 'Shift was successfully updated.' }
        format.json { render :show, status: :ok, location: @shift }
      else
        format.html { render :edit }
        format.json { render json: @shift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shifts/1
  # DELETE /shifts/1.json
  def destroy
    @assignment = @shift.assignment    
    @shift.destroy
    respond_to do |format|
      @shifts = @assignment.shifts.select{ |s| can? :read, s}.to_a.paginate(:page => params[:shifts_page], :per_page => 8)       
      format.js
      format.html { redirect_to shifts_url, notice: 'Shift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def start_now
    @shift.start_now
    redirect_to :home, notice: 'Shift was started'
  end

  def end_now
    @shift.end_now
    redirect_to :home, notice: 'Shift was ended'    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shift
      @shift = Shift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shift_params
      params.require(:shift).permit(:assignment_id, :date, :start_time, :end_time, :notes)
    end
end

app/views/shifts/_form.html.erb
<%= simple_form_for(@shift) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :assignment_id %>
    <%= f.text_field :date, :id => "shiftdatepicker", label: 'Date', :value => Date.strptime(@shift.date.to_s, "%Y-%m-%d").to_date.strftime("%m/%d/%Y") %>
    <%= f.input :start_time, :ampm => true, :label => "Start Time" %>
    <%= f.input :end_time, :default => 3.hours.from_now, :ampm => true, :label => "Start Time"  %>
    <%= f.input :notes %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/shifts/_incomplete_shift_list.html.erb
<fieldset>
  <legend><h3>Incomplete Shifts</h3></legend>
  <table>
    <thead>
      <tr>
        <th>Employee</th>
        <th>Phone</th>
        <th>Assignment</th>
        <th>Date</th>
        <th>Start time</th>
        <th>End time</th>
        <% if can? :read, Shift %>
          <th></th>
        <% end %>
        <% if can? :update, Shift %>
          <th></th>
        <% end %>
        <% if can? :destroy, Shift %>
          <th></th>
        <% end %>   
      </tr>
    </thead>

    <tbody>
      <% @incomplete_shifts.each do |shift| %>
        <tr>
          <td><%= link_to shift.assignment.employee.proper_name, employee_path(shift.assignment.employee_id) %></td>
          <td><a href="tel:<%= number_to_phone shift.assignment.employee.phone %>"><%= number_to_phone shift.assignment.employee.phone %></a></td>        
          <td><%= link_to shift.assignment_id, assignment_path(shift.assignment) %></td>
          <td><%= shift.date.strftime("%m/%d/%y") %></td>
          <td><%= shift.start_time.strftime("%I:%M %p") %></td>
          <td><%= shift.end_time.strftime("%I:%M %p") %></td>
          <% if can? :read, shift %>
            <td><%= link_to 'Add Job', shift %></td>
          <% end %>
          <% if can? :update, shift %>
            <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
          <% end %>
          <% if can? :destroy, shift %>
            <td><%= link_to 'Destroy', shift, method: :delete %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @incomplete_shifts, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "incomplete_shifts_page" %>
</fieldset>

app/views/shifts/_new_job_form.html.erb
<div id="new_job_form">
  <h5>Add New Job</h5>
  <%= simple_form_for @job, remote: true do |f| %>
    <%= f.error_notification %>
    <%= f.input :name %>
    <%= f.input :descrption, as: :text %>
    <%= f.input :active, as: :boolean %>
    <div class="form-actions">
      <%= f.submit nil, class: 'button small radius' %>
      <%= link_to 'Cancel', assignment_path(params[:assignment_id]), class: 'button small radius alert' %>
   </div>
<% end %>
</div>

app/views/shifts/_new_shift_form.html.erb
<script>
  $(function(){
    $('#shiftassignmentdatepicker').fdatetimepicker({
        minView: '2',
        format: 'mm/dd/yyyy'
    });
  });
</script>
<div id="new_shift_form">
  <h5>Add New Shift</h5>
  <%= simple_form_for @shift, remote: true do |f| %>
    <%= f.error_notification %>
    <%= f.text_field :date, :label => "Date", :value => Date.current.to_date.strftime("%m/%d/%Y"), :id => "shiftassignmentdatepicker" %>
    <%= f.input :start_time %>
    <%= f.input :end_time, :default => 3.hours.from_now %>
    <%= f.input :notes %>
    <%= f.input :assignment_id, as: :hidden, input_html: { value: params[:assignment_id] } %>

    <div class="form-actions">
      <%= f.submit nil, class: 'button small radius' %>
      <%= link_to 'Cancel', assignment_path(params[:assignment_id]), class: 'button small radius alert' %>
    </div>
  <% end %>
</div>

app/views/shifts/_shift_details.html.erb
<fieldset>
  <legend><h3>Shift for <%= @shift.assignment.employee.proper_name %></h3></legend>
  <p>
    <strong>Shift ID:</strong>
    <%= @shift.id %>
  </p>
  <p>
    <strong>Assignment ID:</strong>
    <%= link_to @shift.assignment_id, assignment_path(@shift.assignment) %>
  </p>

  <p>
    <strong>Store:</strong>
    <%= link_to @shift.assignment.store.name, store_path(@shift.assignment.store) %>
  </p>  

  <p>
    <strong>Date:</strong>
    <%= @shift.date.strftime("%m/%d/%y") %>
  </p>

  <p>
    <strong>Start time:</strong>
    <%= (@shift.start_time).strftime("%I:%M %p") %>
  </p>

  <p>
    <strong>End time:</strong>
    <%= (@shift.end_time).strftime("%I:%M %p") %>
  </p>

  <p>
    <strong>Notes:</strong>
    <%= @shift.notes %>
  </p>
</fieldset>

app/views/shifts/_shift_job_list.html.erb
<div id="shift_job_list">
  <% if @shift_jobs.count > 0 then %>
    <h4>Jobs for This Shift</h4>
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
          <% if can? :update, ShiftJob %>
            <th>Edit</th>
          <% end %>
          <% if can? :destroy, ShiftJob %>
            <td>Delete</th>
          <% end %>
        </tr>
      </thead>
      <tbody>
        <% @shift_jobs.each do |s| %>
          <tr>
            <td><%= link_to s.job.name, job_path(s.job) %></td>
            <td><%= s.job.description %></td>       
            <% if can? :update, ShiftJob %>                  
              <td><%= link_to 'Edit', edit_shift_job_path(s) %></td>
            <% end %>
            <% if can? :destroy, ShiftJob %> 
              <td><%= link_to 'Destroy', shift_job_path(s), :method => :delete, remote: true %></td>         
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
  <%= will_paginate @shift_jobs, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "shift_jobs_page" %>
  <% else %>
    <h4>No Jobs Currently Assigned to this Shift</h4>
  <% end %>
</div>

app/views/shifts/_shift_list.html.erb
<% unless @shifts.nil? %>
  <fieldset>
    <legend><h3>Listing Shifts</h3></legend>
    <table>
      <thead>
        <tr>
          <th>Assignment</th>
          <th>Date</th>
          <th>Start time</th>
          <th>End time</th>
          <% if can? :read, Shift %>
            <th></th>
          <% end %>
          <% if can? :update, Shift %>
            <th></th>
          <% end %>
          <% if can? :destroy, Shift %>
            <th></th>
          <% end %>   
        </tr>
      </thead>

      <tbody>
        <% @shifts.each do |shift| %>
          <tr>
            <td><%= shift.assignment_id %></td>
            <td><%= shift.date.strftime("%m/%d/%y") %></td>
            <% if can? :start_shift, shift%>
              <td><%= link_to 'Start Shift', "shifts/#{shift.id}/start_now" %></td>
            <% else %>
              <td><%= (shift.start_time).strftime("%I:%M %p") %></td>
            <% end %>
            <% if can? :end_shift, shift %>
              <td><%= link_to 'End Shift', "shifts/#{shift.id}/end_now" %></td>
            <% else %>
              <td><%= (shift.end_time).strftime("%I:%M %p") %></td>
            <% end %>
            <% if can? :read, shift %>
              <td><%= link_to 'View Details', shift %></td>
            <% end %>
            <% if can? :update, shift %>
              <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
            <% end %>
            <% if can? :destroy, shift %>
              <td><%= link_to 'Destroy', shift, method: :delete %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= will_paginate @shifts, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "shifts_page" %>
  </fieldset>
<% else %>
  <h3>No Shifts to Display</h3>
<% end %>

app/views/shifts/_today_shift_list.html.erb
<fieldset>
  <legend><h3>Today's Shifts</h3></legend>
  <table>
    <thead>
      <tr>
        <th>Employee</th>
        <th>Phone</th>
        <th>Assignment</th>
        <th>Date</th>
        <th>Start time</th>
        <th>End time</th>
        <% if can? :read, Shift %>
          <th></th>
        <% end %>
        <% if can? :update, Shift %>
          <th></th>
        <% end %>
        <% if can? :destroy, Shift %>
          <th></th>
        <% end %>   
      </tr>
    </thead>

    <tbody>
      <% @today_shifts.each do |shift| %>
        <tr>
          <td><%= link_to shift.assignment.employee.proper_name, employee_path(shift.assignment.employee_id) %></td>
          <td><a href="tel:<%= number_to_phone shift.assignment.employee.phone %>"><%= number_to_phone shift.assignment.employee.phone %></a></td>
          <td><%= link_to shift.assignment_id, assignment_path(shift.assignment) %></td>
          <td><%= shift.date.strftime("%m/%d/%y") %></td>
          <td><%= shift.start_time.strftime("%I:%M %p") %></td>
          <td><%= shift.end_time.strftime("%I:%M %p") %></td>
          <% if can? :read, shift %>
            <td><%= link_to 'Add Job', shift %></td>
          <% end %>
          <% if can? :update, shift %>
            <td><%= link_to 'Edit', edit_shift_path(shift) %></td>
          <% end %>
          <% if can? :destroy, shift %>
            <td><%= link_to 'Destroy', shift, method: :delete %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= will_paginate @today_shifts, :previous_label => "Previous&nbsp;", :next_label => "&nbsp;Next", :param_name => "today_shifts_page" %>
</fieldset>

app/views/shifts/create.js.erb
$('#new_shift_form').remove();
$('#new_shift_link').show();


$('#shift_list').replaceWith('<%= j render("assignments/shift_history") %>');

app/views/shifts/destroy.js.erb
$('#shift_list').replaceWith('<%= j render("assignments/shift_history") %>');

app/views/shifts/edit.html.erb
<h1>Editing Shift</h1>

<%= render 'form' %>

app/views/shifts/index.html.erb
<%= render partial: "partials/index_structure_2", locals: {model_name: "shift", 
                                                         primary: "shift_list", 
                                                         secondary: nil,
                                                         sidebar: nil} %>

app/views/shifts/new.html.erb
<h1>New Shift</h1>

<%= render 'form' %>

app/views/shifts/show.html.erb
<div class="row">
  <div class="small-7 columns">
    <%= render partial: "shift_details" %>
  </div>
  <div class="small-5 columns">  
    <%= render partial: "shift_job_list"%>
    <% if can? :create, ShiftJob %>
      <%= link_to(new_shift_job_path(shift_id: @shift.id), class: 'button small radius', id: 'new_shift_job_link', remote: true) do %>
        New Job Association
      <% end %>    
    <% end %>
  </div>

</div>

<!-- Add buttons to list all, edit project or destroy object -->
<%= render partial: "partials/object_options", locals: {model_name: "shift", object: @shift}  %>